name: shield
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  hive: ^2.2.3
  timeago: ^3.5.0
  firebase_auth: ^4.7.3
  google_sign_in: ^6.1.4
  image_picker: ^1.0.2
  cloud_firestore: ^4.8.5
  firebase_core: ^2.15.1
  animated_bottom_navigation_bar: ^1.2.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  hive_generator: ^2.0.1
  firebase_storage: ^11.2.6
  map_location_picker: ^1.2.6
  intl: ^0.18.1
  just_audio: ^0.9.34
  audioplayers: ^5.1.0
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
flutter:


  uses-material-design: true
  assets:
    - "assets/sample_data/volunteers_list.json"
    - "assets/config_data/app_config.json"
    - "assets/thumb/volunteers_page_thumb.png"
    - "assets/thumb/guides_cover.png"
    - "assets/sample_data/guides_list.json"
    - "assets/alert_sound.mp3"
