// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_J7ng_nhHq5DIVhsqae1jQJSY_sTWG0',
    appId: '1:246633224512:web:863d5b14aede2f45f982a5',
    messagingSenderId: '246633224512',
    projectId: 'shield-cosmic',
    authDomain: 'shield-cosmic.firebaseapp.com',
    storageBucket: 'shield-cosmic.appspot.com',
    measurementId: 'G-RYLH9475B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6j2Wy5Leg118WbYNLDahsf3zXyImp-g0',
    appId: '1:246633224512:android:89e1ad985a5bb572f982a5',
    messagingSenderId: '246633224512',
    projectId: 'shield-cosmic',
    storageBucket: 'shield-cosmic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATINGKmtlAS55yKvCzoHaPo15VsPKjUs8',
    appId: '1:246633224512:ios:068e29b0ec9d3fd3f982a5',
    messagingSenderId: '246633224512',
    projectId: 'shield-cosmic',
    storageBucket: 'shield-cosmic.appspot.com',
    androidClientId: '246633224512-13ev3e48ifds6dfanslu1co7mb04j8tu.apps.googleusercontent.com',
    iosClientId: '246633224512-tvtng79b032t5rjs774p7fo1emkj30b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATINGKmtlAS55yKvCzoHaPo15VsPKjUs8',
    appId: '1:246633224512:ios:c03a6d7221817b58f982a5',
    messagingSenderId: '246633224512',
    projectId: 'shield-cosmic',
    storageBucket: 'shield-cosmic.appspot.com',
    androidClientId: '246633224512-13ev3e48ifds6dfanslu1co7mb04j8tu.apps.googleusercontent.com',
    iosClientId: '246633224512-in4fbinp0kbh9mbg8u78f0fckhurfd5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shield.RunnerTests',
  );
}
