import 'package:flutter/material.dart';
import 'package:hive_flutter/adapters.dart';
// import 'package:shield/lib/firebase_options.dart';
import 'app/models/guides_model.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';

import 'app/app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  Hive.registerAdapter(GuideStepAdapter()); // Generated by json_serializable
  Hive.registerAdapter(GuidesAdapter()); // Generated by json_serializable
  await Hive.openBox<Guides>('guidesbox');

  runApp(const MyApp());
}
